version: 2.1

jobs:
  build-and-test:
    docker:
        - image: circleci/python@0.2.1
    executor: python/default
    steps:
      - checkout
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
